version: "3.2"

services:
  arango:
    image: arangodb:3.7.2
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "dummyPass"
      ARANGO_STORAGE_ENGINE: rocksdb
    networks:
      back:
        aliases:
          - "arangodb.service.com.br"

networks:
  back: