version: "3.2"

services:
  json-server:
    image: clue/json-server
    entrypoint: 'bash -c "json-server /data/db.json"'
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./negativations.json:/data/db.json
    networks:
      back:
        aliases:
            - "mainframe.service.com.br"

  serasa-challenge:
    build: ./
    restart: always
    ports:
      - "5000:5000"
    networks:
      back:
        aliases:
          - "serasa-challenge.service.com.br"
    depends_on:
      - json-server
      - arango

  arango:
    image: arangodb:3.7.2
    ports:
      - "8529:8529"
    volumes:
      - arango_data_vol:/var/lib/arangodb3
      - ./dump_db:/opt/tools
    environment:
      ARANGO_ROOT_PASSWORD: "dummyPass"
      ARANGO_STORAGE_ENGINE: rocksdb
    networks:
      back:
        aliases:
          - "arangodb.service.com.br"

volumes:
  arango_data_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  back: